site_name: Mathis Gauthey's Website
site_author: Mathis Gauthey
site_description: "Welcome to my personal website. I showcase my projets and share my knowledge here."
site_url: "https://mathis.gauthey.github.io"
repo_url: https://github.com/mathisgauthey/mathisgauthey.github.io
repo_name: mathisgauthey/mathisgauthey.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github
    logo: octicons/code-review-24
  favicon: "assets/favicon.ico"

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - content.action.view
    - content.action.edit
    - navigation.footer
    - header.autohide

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      accent: red
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: red
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: red
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - awesome-pages
  - search
  - blog:
      blog_dir: .
      post_url_format: "{slug}"
      blog_toc: true
      categories_url_format: "{slug}"
  - tags:
      tags_file: tags/index.md
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: mathisgauthey/mathisgauthey.github.io
      branch: main
      enabled: !ENV [CI, false]
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
  - social
  - callouts

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - nl2br
  - admonition
  - pymdownx.details
  - md_in_html
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/mathisgauthey/mathisgauthey.github.io/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.