authors:
  Mathis Gauthey:
    name: Mathis Gauthey  # Author name
    description: Website Owner  # Author description
    avatar: https://github.com/mathisgauthey.png  # Author avatar
    url: https://github.com/mathisgauthey # Author website URL